name: build latest on push to master and release
on:
  push:
    branches:
    - master
    - release/*
    branches-ignore:
    - certified*
jobs:
  operator-sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: operator-sdk
      uses: ./.github/action/operator-sdk
      with:
        args: build lightbend-docker-registry.bintray.io/lightbend/akkacluster-operator:latest
    - name: push to bintray
      run: |
        docker login ${DOCKER_REGISTRY_URL} --username ${DOCKER_USERNAME} --password "${DOCKER_PASSWORD}"
        docker push lightbend-docker-registry.bintray.io/lightbend/akkacluster-operator:latest
      env:
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: goreportcard
      uses: ./.github/action/curl
      with:
        args: -d repo=github.com/lightbend/akka-cluster-operator https://goreportcard.com/checks
