on:
  name: build latest on push to master
  push:
    branches:
    - master
    - release/*
jobs:
  operator-sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: operator-sdk
      uses: ./.github/action/operator-sdk
      with:
        args: build lightbend-docker-registry.bintray.io/lightbend/akkacluster-operator:latest
    - name: bintray login
      uses: actions/docker/login@8cdf801b322af5f369e00d85e9cf3a7122f49108
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: push to bintray
      uses: actions/docker/cli@8cdf801b322af5f369e00d85e9cf3a7122f49108
      with:
        args: push lightbend-docker-registry.bintray.io/lightbend/akkacluster-operator:latest
    - name: goreportcard
      uses: ./.github/action/curl
      with:
        args: -d repo=github.com/lightbend/akka-cluster-operator https://goreportcard.com/checks
